# frozen_string_literal: true

source 'https://rubygems.org'

gem 'logger'

group :development, :test do
  gem 'dotenv'
  gem 'pry'
  gem 'rspec'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'solargraph'
end
