#!/usr/bin/env bash

cd "$(dirname "$0")/../../infra" || exit
api_base=$(terraform output -json | jq -r .api_base_url.value)

curl -v "$api_base/orders" \
  -H "content-type: application/json" \
  -d '{ "customer_id": "0xAB", "total": 99 }'
