infra-plan:
	$(MAKE) -C infra plan

infra-apply:
	$(MAKE) -C infra apply

infra-destroy:
	$(MAKE) -C infra destroy

app-deps-install:
	$(MAKE) -C src deps-install

app-console:
	$(MAKE) -C src console

app-test-suite:
	$(MAKE) -C src test-suite
