#!/usr/bin/env bash

set -euxo pipefail

main () {
  # shellcheck disable=SC2154
  ACTION=$action

  case "$ACTION" in
    "c" | "create")
      create_s3_bucket
      create_dynamodb_table
      ;;
    "d" | "destroy")
      destroy
      ;;
    *)
      echo "Unknown action: $ACTION"
      exit 1
      ;;
  esac
}

create_s3_bucket () {
  local TF_OBJECT
  local ROLE_ARN
  # shellcheck disable=SC2154
  local REGION=$region

  TF_OBJECT=$(tf_object)
  ROLE_ARN=$(aws sts get-caller-identity | jq -r ".Arn")

  aws s3 mb "s3://${TF_OBJECT}" \
    --region "${REGION}"
  aws s3api put-public-access-block \
    --bucket "${TF_OBJECT}" \
    --public-access-block-configuration "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
  sed \
    -e "s/RESOURCE/arn:aws:s3:::${TF_OBJECT}/g" \
    -e "s|ARN|${ROLE_ARN}|g" "$(dirname "$0")/policy-template.json" \
    > policy.json
  aws s3api put-bucket-policy \
    --bucket "${TF_OBJECT}" \
    --policy file://policy.json
  aws s3api put-bucket-versioning \
    --bucket "${TF_OBJECT}" \
    --versioning-configuration Status=Enabled
  rm policy.json
}

create_dynamodb_table () {
  local TF_OBJECT
  local REGION=$region

  TF_OBJECT=$(tf_object)
  aws dynamodb create-table \
    --table-name "${TF_OBJECT}" \
    --attribute-definitions AttributeName=LockID,AttributeType=S \
    --key-schema AttributeName=LockID,KeyType=HASH \
    --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 \
    --region "${REGION}"
}

destroy () {
  # shellcheck disable=SC2154
  local REGION=$region
  local TF_OBJECT

  TF_OBJECT=$(tf_object)
  # TODO: remove tf state file
  aws s3 rb "s3://${TF_OBJECT}"
  aws dynamodb delete-table \
    --table-name "${TF_OBJECT}" \
    --region "${REGION}"
}

tf_object () {
  # shellcheck disable=SC2154
  local PROJECT=$project
  # shellcheck disable=SC2154
  local REGION=$region
  # shellcheck disable=SC2154
  local ENVIRONMENT=$environment

  echo "terraform-${PROJECT}-${REGION}-${ENVIRONMENT}"
}

main
