# frozen_string_literal: true

source 'https://rubygems.org'

gem 'aws-sdk-dynamodb', '~> 1.132'
gem 'aws-sdk-sqs', '~> 1.89'
gem 'dry-validation', '~> 1.10'

group :development, :test do
  gem 'dotenv'
  gem 'pry'
  gem 'rspec'
  gem 'rubocop'
  gem 'solargraph'
end
